version: "3.9"

services:
  stashbin:
    image: stashbin-backend
    container_name: stashbin-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GIN_MODE: release
      DB_URI:
      PORTS: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped


